services:
  - type: web
    name: af-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5005
      - key: MONGO_URI
        sync: false 