services:
  - type: web
    name: af-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5005
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false 